### ISSUE TITLE
Synthetic locations - unknown location

### ISSUE THREAD

**Issue by JACONDE** [dynatrace-oss/dynatrace-monitoring-as-code#59]
I found already a couple of times that when executing the synthetic set-up the Synthetic locations just stop to work with the unknown location error- Find below the error I've got:

_020-11-20T15:28:28.9848035Z 2020-11-20 15:28:28 INFO  Dynatrace Monitoring as Code v1.0.0
2020-11-20T15:28:29.0296087Z 2020-11-20 15:28:29 INFO  Executing projects in this order: 
2020-11-20T15:28:29.0296961Z 2020-11-20 15:28:29 INFO  	1: projects\Application (9 configs)
2020-11-20T15:28:29.0297515Z 2020-11-20 15:28:29 INFO  Processing environment Germany...
2020-11-20T15:28:29.0297841Z 2020-11-20 15:28:29 INFO  	Processing project projects\Application...
2020-11-20T15:28:29.8322009Z 2020-11-20 15:28:29 ERROR Deployment to Germany failed with error Failed to upsert DT object GE_APP-123_XXXXX (HTTP 400)!
2020-11-20T15:28:29.8323595Z     Response was: {"error":{"code":400,"message":"Unknown location(s): [GEOLOCATION-5760CF2C54BBEE66]"}}, responsible config: projects\Application\synthetic-monitor\synthetic-monitor.json_

**Comment by JACONDE** [comment]
It was working fine at 3.29 and stopped to work at 4.30. Same behaviour happen yesterday,

**Comment by didiladi** [comment]
That is really interesting. Can you tell us more about the specific geolocation you are trying to create the synthetic test for? Is it a private synthetic location (private active gate), or is it a public one?

**Comment by JACONDE** [comment]
It is a public location

**Comment by didiladi** [comment]
I just had a chat with one of the synthetic engineers here at Dynatrace. In version 206 there was a bug in the product, which remapped the id of the synthetic location. However, the issue is fixed by now - the old id should be valid again. Can you try again (with `GEOLOCATION-5760CF2C54BBEE66`)?

**Comment by JACONDE** [comment]
[GEOLOCATION-5760CF2C54BBEE66] still fails, but the new one GEOLOCATION-CFA479BB38E4A52B works fine now !

**Comment by didiladi** [comment]
Perfect, glad to hear!
